Add new Devops agent for Python
kubesphere-sigs/ks-devops-helm-chart pull request #30
Opened 2021-10-25 15:13 UTC by mangoGoForward

### What type of PR is this?

/kind feature

### What this PR does / why we need it:
Currently, we've add some fresh DevOps agents in https://github.com/kubesphere/devops-agent, The PR try to add remained config to jenkins-casc-config

### Which issue(s) this PR fixes:

Fixes #28

2021-10-31 07:12 UTC, mangoGoForward commented
Could you help me to review this PR and get me some suggestions? @JohnNiang

2021-10-31 07:13 UTC, mangoGoForward commented
/kind hacktoberfest-accepted

2021-10-31 11:20 UTC, LinuxSuRen commented
> /kind hacktoberfest-accepted

This kind of action should be taken by the maintainer. Any way, thanks for your reminder.

2021-10-31 14:10 UTC, mangoGoForward commented
> > /kind hacktoberfest-accepted
> 
> This kind of action should be taken by the maintainer.
> 
> I'll test it later.
> 
> Anyway, thanks for your reminder.

Haha, It's my misunderstanding about the activity's description. Thanks a lot.

2021-11-01 02:48 UTC, JohnNiang commented on charts/ks-devops/charts/jenkins/values.yaml
> +      Tag: v3.1.0
Currently, [docker image](https://hub.docker.com/r/kubespheredev/builder-dotnet/tags) of `builder-dotnet` has gone. When it is getting ready, we'll merge this PR for further test.

2021-11-01 06:18 UTC, mangoGoForward commented on charts/ks-devops/charts/jenkins/values.yaml
> +      Tag: v3.1.0
How about remove `builder-dotnet`, only support `builder-python` in this PR, and create a new PR for `builder-dotnet`?

2021-11-01 06:19 UTC, JohnNiang commented on charts/ks-devops/charts/jenkins/values.yaml
> +      Tag: v3.1.0
That would be better.

2021-11-01 06:32 UTC, mangoGoForward commented on charts/ks-devops/charts/jenkins/values.yaml
> +      Tag: v3.1.0
Done.

2021-11-01 08:06 UTC, LinuxSuRen reviewed
I have tested it manually. It works well. See the Jenkinsfile below:
```groovy
pipeline {
    agent {
        label 'python'
    }
    
    stages {
        stage('test') {
            steps {
                sh '''
                python -V
                '''
            }
        }
    }
}
```

Test output:
```shell
Running on python-t742f in /home/jenkins/agent/workspace/test
[Pipeline] {
[Pipeline] stage
[Pipeline] { (test)
[Pipeline] sh
+ python -V
Python 2.7.13
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

/lgtm

@mangoGoForward Thanks for your contribution!

2021-11-01 14:52 UTC, mangoGoForward commented on charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
> +                    mountPath: "/home/jenkins/python/app"
It just a habit for me, and specify the storage location of python service. It seems unnecessary in this mount path, I want to remove the suffix `/app`, make it more clear.

2021-11-01 15:24 UTC, mangoGoForward commented on charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
> +                    mountPath: "/home/jenkins/python/app"
Thanks your advice. But there may should specify the third-party library installed by `pip`, How about change this path to  cache those library?

2021-11-01 15:27 UTC, JohnNiang commented on charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
> +                    mountPath: "/home/jenkins/python/app"
I searched from GitHub cache action, and there are two references for us about Python cache: 
- https://github.com/actions/cache/blob/main/examples.md#python---pip
- https://github.com/actions/cache/blob/main/examples.md#python---pipenv

2021-11-01 15:50 UTC, mangoGoForward commented on charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
> +                    mountPath: "/home/jenkins/python/app"
Done.

2021-11-01 15:52 UTC, JohnNiang commented
/lgtm

2021-11-02 06:13 UTC, LinuxSuRen commented
hi @mangoGoForward and @JohnNiang , in order to avoid unnecessary problems during the v3.2.0 release time period. I'll hold this PR until KubeSphere v3.2.0 is ready.
/hold

2021-11-03 13:43 UTC, JohnNiang commented
/retitle Add new Devops agent for Python

2021-11-03 13:45 UTC, JohnNiang commented
Hi @LinuxSuRen , since that [KubeSphere 3.2.0](https://github.com/kubesphere/kubesphere/releases/tag/v3.2.0) has been released and announced, we can continue to push this forward.

2021-11-03 14:04 UTC, JohnNiang commented on charts/ks-devops/charts/jenkins/values.yaml
> +    Python:
Hi @mangoGoForward , can you make those variable name camel-case? Please don't forget change its references.

2021-11-03 15:38 UTC, mangoGoForward commented on charts/ks-devops/charts/jenkins/values.yaml
> +    Python:
Ok.

2021-11-03 15:44 UTC, mangoGoForward commented on charts/ks-devops/charts/jenkins/values.yaml
> +    Python:
Done.

2021-11-03 15:46 UTC, JohnNiang requested changes

2021-11-03 15:46 UTC, JohnNiang commented on charts/ks-devops/charts/jenkins/values.yaml
> +      Image: builder-python
Please don't forget the variable names `Image` and `Tag`. : P

2021-11-03 16:09 UTC, mangoGoForward commented
Do we have schedule to refactor this file with caml-case code style? And when we add more pod template, the file seems will be poor readability.

2021-11-04 09:05 UTC, JohnNiang commented
> Do we have schedule to refactor this file with caml-case code style? And when we add more pod template, the file seems will be poor readability.

Please follow up https://github.com/kubesphere-sigs/ks-devops-helm-chart/issues/26

2021-11-04 09:06 UTC, JohnNiang commented
/lgtm

2021-11-08 03:08 UTC, JohnNiang commented
/unhold

2021-11-08 13:21 UTC, JohnNiang commented
/ping @kubesphere-sigs/sig-devops

2021-11-09 11:44 UTC, LinuxSuRen requested changes
hi @mangoGoForward it looks like everything is great. Before we merge it, you need to fix the conficts.

2021-11-09 13:32 UTC, LinuxSuRen reviewed
/lgtm

2021-11-09 13:32 UTC, merged

2021-11-09 13:33 UTC, mangoGoForward commented
> hi @mangoGoForward it looks like everything is great. Before we merge it, you need to fix the conficts.

Solved. The git configuration actually has some errors in my local environment, thanks your reminder.