add new devops agent for jdk11
kubesphere-sigs/ks-devops-helm-chart pull request #39
Opened 2021-11-03 02:04 UTC by mangoGoForward

### What type of PR is this?

/kind feature

### What this PR does / why we need it:
please see #28.

### Which issue(s) this PR fixes:

Fixes #28 .

### How to test?

1. Install ks-devops via helm charts
```
make install-chart
```
2. Create a test Pipeline
Pipeline script example:
```
pipeline {
  agent {
    node {
      label 'maven'
    }
  }
  stages {
    stage('Greet') {
      steps {
        container('maven') {
          sh '''mvn -version'''
        }
      }
    }
  }
}

```

2021-11-03 02:08 UTC, JohnNiang requested changes

2021-11-03 02:08 UTC, JohnNiang commented on charts/ks-devops/charts/jenkins/values.yaml
> +    MavenJdk11:
We have a plan to refine the naming method in values.yaml for Jenkins chart, please see also https://github.com/kubesphere-sigs/ks-devops-helm-chart/issues/26.

So I suggest to change variable name `MavenJdk11` to `mavenJDK11`

2021-11-03 02:26 UTC, mangoGoForward commented on charts/ks-devops/charts/jenkins/values.yaml
> +    MavenJdk11:
I see

2021-11-03 02:29 UTC, mangoGoForward commented on charts/ks-devops/charts/jenkins/values.yaml
> +    MavenJdk11:
Done.

2021-11-09 07:09 UTC, LinuxSuRen requested changes

2021-11-09 07:09 UTC, LinuxSuRen commented on charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
> +                label: "maven"
There are two podTemplates that have the same label `maven. How to use jdk11?

2021-11-09 08:04 UTC, mangoGoForward commented on charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
> +                label: "maven"
No opinion.

2021-11-09 08:50 UTC, mangoGoForward commented on charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
> +                label: "maven"
Done.

2021-11-09 09:01 UTC, mangoGoForward commented on charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
> +                label: "maven"
Done.

2021-11-09 11:33 UTC, LinuxSuRen commented on charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
> +                label: "jdk11"
I prefer to add multiple labels here. For example, you can put three labels `jdk11 maven java`.

Why not just add one label? It's useful when users don't care about the version of JDK, they might just want to have a JDK environment.

2021-11-09 13:52 UTC, AbdelouahabMbarki commented on charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
> +                label: "jdk11"
i agree ,it will leave more space for people who use other tools like gradle

2021-11-10 05:52 UTC, LinuxSuRen reviewed
/lgtm

2021-11-30 06:41 UTC, JohnNiang approved these changes
/lgtm

2021-12-20 08:13 UTC, LinuxSuRen reviewed
/approve

2021-12-20 08:14 UTC, merged